### ISSUE TITLE
Create R package

### ISSUE THREAD

**Issue by mollyow** [UChicago-pol-methods/banditsCI#2]
**References**

 - I think [this](https://web.mit.edu/insong/www/pdf/rpackage_instructions.pdf) is a good start.
   - I'd like to use the instructions starting on section 3 p. 7
 - Hadley Wickham and Jennifer Bryan have a much more detailed bookdown [here](https://r-pkgs.org/); may be helpful for debugging

----

**To-do to get started**

- [x] Create a branch for package development. 
- [x] Determine which functions we actually need in [`/code`](https://github.com/UChicago-pol-methods/bandits_CI/tree/main/code) for running simulations and generating confidence intervals. Consolidate code and delete everything we don't need. 
- [x] Create a minimal working version of the package. We'll fill in details and write up vignettes as we go. 
    - [x] Move package up to main level of repository
- [x] Once the minimal working version is working, we'll merge the branch into main. 
- [x] Working on vignettes: See e.g., https://github.com/DeclareDesign/estimatr/tree/main/vignettes @mollyow 
    - [x] Tidy up the contextual vignette
    - [x] Write non-contextual vignette
    - [x] Add further notes; update 4x arms figure to label as groups that each arm is best for; add more notes on how policy is learned; add commentary on uniform/non-contextual two-point regarding relative performance
    - [x] Check against Python simulated settings to make sure we get the same confidence intervals with both contextual and non-contextual data. 
      - [x] #15
      - [x] #14
      - [x] We still need to add in something like [`ridge_muhat_lfo_pai()`](https://github.com/gsbDBI/contextual_bandits_evaluation/blob/f9f2100aea74addf4fa4f52807bd224bde556e9f/adaptive/ridge.py#L85) to LFO estimation; should we do this as a function (not very generalizable) or just write up in the vignette?
    - [x] Add plotting function after estimating response / treatment effects and CIs, like what is in [`starting_script.R`](https://github.com/UChicago-pol-methods/bandits_CI/blob/b03858bf2ba94760523c1df81f0c8fb3f0702572/code/starting_script.R#L91C1-L98C30) right now. @mollyow
